version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    docker:
      - image: prajjmondal/url_shortner:0.1.0
      - image: circleci/mysql:latest
        environment:
          MYSQL_DATABASE: url_shortcodes
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: enFn8dsmQBi4gkcP
          MYSQL_USER: url_shortner
          MYSQL_PASSWORD: testpassword
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx
    steps:
      - checkout
      # - python/load-cache
      - python/install-deps
      # - run: pip install -r requirements/dev.txt
      - python/save-cache
      - run:
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          command: |
            mysql -h 127.0.0.1 -u url_shortner --password=testpassword  url_shortcodes < tests/test_sql.sql
            mysql -h 127.0.0.1 -u url_shortner --password=testpassword  --execute="SELECT * FROM url_shortcodes.urllist"
      - run: pytest -v
workflows:
  main:
    jobs:
      - build-and-test:
          context: url_shortner_main_context
