version: 2.1

orbs:
  python: circleci/python@0.3.2
  heroku: circleci/heroku@1.2.1

executors:
  docker-with-sql:
    # The primary image is the docker image of the repo and the secondary image is a
    # mysql server. The two are in a common network where ports exposed on the primary 
    # container are available on localhost.
    docker:
      - image: prajjmondal/url_shortner:0.1.0
      - image: circleci/mysql:latest
        environment:
          MYSQL_DATABASE: url_shortcodes
          MYSQL_ROOT_HOST: "%"
          MYSQL_ROOT_PASSWORD: enFn8dsmQBi4gkcP
          MYSQL_USER: url_shortner
          MYSQL_PASSWORD: testpassword
        command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx

commands:
  wait-for-mysql-server:
    description: "Waiting for the mysql server to startup"
    steps:
      - run:
          command: |
            for i in `seq 1 10`;
            do
              nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1

  populate-table:
    description: "Populate the test db with data and print it out"
    steps:
      - run:
          command: |
            mysql -h 127.0.0.1 -u url_shortner --password=testpassword  url_shortcodes < tests/test_sql.sql
            mysql -h 127.0.0.1 -u url_shortner --password=testpassword  --execute="SELECT * FROM url_shortcodes.urllist"

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      # - python/load-cache # Caching gives - Cannot mkdir: Permission denied tar: home/circleci/.local/lib/python3.8/si: exit status 2
      - python/install-deps
      # - python/save-cache # No point saving to cache, since I can't load cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    executor: docker-with-sql
    steps:
      - attach_workspace:
          at: .
      - wait-for-mysql-server
      - populate-table
      - run: pytest -v

workflows:
  build_and_test_for_prs:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - test:
          context: url_shortner_main_context
          requires:
            - build

  build_and_deploy_for_master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - test:
          context: url_shortner_main_context
          requires:
            - build
      - hold_for_approval:
          type: approval
          requires:
            - test
      - heroku/install:
          requires:
            - hold_for_approval
      - heroku/deploy-via-git          
